ALTER TABLE manager_sessions ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES stores(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS store_heads_up (
    store_id BIGINT PRIMARY KEY REFERENCES stores(id) ON DELETE CASCADE,
    message TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
